services:
  consul:
    image: consul
    ports:
      - 8500:8500
    command: agent -dev -client 0.0.0.0

  pg:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
