apiVersion: v1
kind: Service
metadata:
  namespace: macrostack
  name: gateway-service
  labels:
    app: gateway
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gateway
