[package]
name = "macrostack-protocol"
version = "0.1.0"
edition = "2021"

[features]
default = ["hello"]
hello = []

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
