[package]
name = "macrostack-tracing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

tracing = { workspace = true }
